### ISSUE TITLE
Read tsm file error

### ISSUE THREAD

**Issue by Subsegment** [cnosdb/cnosdb-isipho#30]
**Description**

when read a tsm file which has float data,it will case 

> error decoding block data: ReadTsmErr { reason: "unexpected end of block" }
thread 'kvcore::test::test_read' panicked at 'error decoding block data: ReadTsmErr { reason: "unexpected end of block" }', tskv/src/kvcore.rs:211:64

**How to reproduce**
`cargo test --package tskv --lib kvcore::test::test_read -- --exact`

**suggestion**
modify
tskv/src/tsm/reader.rs:74
```
                coders::float::decode_influxdb(&data[idx..], &mut val)
```

```
                coders::float::decode(&data[idx..], &mut val)
```

**Comment by roseboy-liu** [comment]
please fix，thx
